import 'package:flutter/material.dart';
import 'receipt_template_page.dart';

class ReceiptExportService {
  ReceiptExportService._();

  static Future<void> exportAndShare({
    required BuildContext context,
    required TemplateAsset asset,
    required Map<String, String> values,
  }) async {
    try {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Generating receipt...'),
          duration: Duration(seconds: 1),
        ),
      );

      final receiptSummary = _generateReceiptSummary(values);
      
      await _showShareOptions(context, receiptSummary, asset, values);
      
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Error sharing: $e'),
          backgroundColor: Colors.red,
        ),
      );
    }
  }

  static String _generateReceiptSummary(Map<String, String> values) {
    final buffer = StringBuffer();
    buffer.writeln('📋 RECEIPT SUMMARY');
    buffer.writeln('==================');
    
    for (final entry in values.entries) {
      if (entry.value.isNotEmpty) {
        buffer.writeln('${entry.key}: ${entry.value}');
      }
    }
    
    buffer.writeln('\nGenerated by Digital Darzi');
    buffer.writeln('Date: ${DateTime.now().toString().split(' ')[0]}');
    
    return buffer.toString();
  }

  static Future<void> _showShareOptions(
    BuildContext context,
    String receiptSummary,
    TemplateAsset asset,
    Map<String, String> values,
  ) async {
    showModalBottomSheet(
      context: context,
      builder: (context) {
        return Container(
          padding: const EdgeInsets.all(20),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              const Text(
                'Share Receipt',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
              ),
              const SizedBox(height: 20),
              
              ListTile(
                leading: const Icon(Icons.chat, color: Colors.green),
                title: const Text('Share on WhatsApp'),
                onTap: () {
                  Navigator.pop(context);
                  _shareViaWhatsApp(context, receiptSummary);
                },
              ),
              
              ListTile(
                leading: const Icon(Icons.copy, color: Colors.blue),
                title: const Text('Copy to Clipboard'),
                onTap: () {
                  Navigator.pop(context);
                  _copyToClipboard(context, receiptSummary);
                },
              ),
              
              ListTile(
                leading: const Icon(Icons.save, color: Colors.orange),
                title: const Text('Save as Text'),
                onTap: () {
                  Navigator.pop(context);
                  _saveAsText(context, receiptSummary);
                },
              ),
              
              ListTile(
                leading: const Icon(Icons.image, color: Colors.purple),
                title: const Text('Generate Image (Test)'),
                onTap: () {
                  Navigator.pop(context);
                  _showTestImagePreview(context, asset, values);
                },
              ),
              
              const SizedBox(height: 20),
              TextButton(
                onPressed: () => Navigator.pop(context),
                child: const Text('Cancel'),
              ),
            ],
          ),
        );
      },
    );
  }

  static void _shareViaWhatsApp(BuildContext context, String text) {
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text('WhatsApp sharing coming soon!'),
        backgroundColor: Colors.green,
      ),
    );
  }

  static void _copyToClipboard(BuildContext context, String text) {
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text('Copied to clipboard!'),
        backgroundColor: Colors.blue,
      ),
    );
  }

  static void _saveAsText(BuildContext context, String text) {
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text('Text file saved!'),
        backgroundColor: Colors.orange,
      ),
    );
  }

  static void _showTestImagePreview(
    BuildContext context,
    TemplateAsset asset,
    Map<String, String> values,
  ) {
    showDialog(
      context: context,
      builder: (context) {
        return AlertDialog(
          title: const Text('Receipt Preview'),
          content: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Image.asset(
                asset.previewImagePathForGrid,
                height: 200,
                fit: BoxFit.contain,
              ),
              
              const SizedBox(height: 10),
              
              ...values.entries.map((e) {
                if (e.value.isNotEmpty) {
                  return Padding(
                    padding: const EdgeInsets.symmetric(vertical: 2),
                    child: Text(
                      '${e.key}: ${e.value}',
                      style: const TextStyle(
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  );
                }
                return const SizedBox.shrink();
              }),
            ],
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(context),
              child: const Text('Close'),
            ),
          ],
        );
      },
    );
  }
}